force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <description>This is a simple description</description>
    <label>Custom Event</label>
    <nameField>
        <label>Custom Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The day the event started</description>
    <inlineHelpText>this is a field to hold information about the day of the event</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event_Session__c/Event_Session__c.object-meta.xml
<CustomObject>
    <description>A subsession</description>
    <label>Event Session</label>
    <nameField>
        <label>Event Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Session__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <description>This is a relationship between father and child</description>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Sessions</relationshipLabel>
    <relationshipName>Event_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End_Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EventSessionController.cls
public class EventSessionController {
    public static void createEventSessions(Date startDate, Date endDate, Integer listSize, String Id){
        List<Event_Session__c> sessions = new List<Event_Session__c>();
        
        for(Integer i = 0; i<listSize; i ++){
            Event_Session__c event = new Event_Session__c();
            event.Start_Date__c = startDate + i;
            event.End_Date__c = endDate + i;
            event.Custom_Event__c = Id;
            sessions.add(event);
        }
        insert sessions;
    }
    public static void createEventSession(Date startDate, Date endDate , String Id){
        Event_Session__c event = new Event_Session__c();
        event.Start_Date__c = startDate;
        event.End_Date__c = endDate;
        event.Custom_Event__c = Id;
        
        try{
           insert event; 
        }catch(DmlException e){
            System.debug('the exeption is' + e.getMessage());
        }
        
        
        
    }
    public static void updateSession(String Name, String sessionId){
        Event_Session__c se = [SELECT id,Name FROM Event_Session__c WHERE id = :sessionId];
        
        se.Name = Name;
        se.Id = sessionId;
        
        update se;
    }
    public static void getSessionWithMap(String Name){
        Map<String,Event_Session__c> myMap = new Map<String,Event_Session__c>([SELECT id, Name FROM Event_Session__c]);
        System.debug(' ' + myMap);
        List<Event_Session__c> sessions = myMap.values();
        
        for(Event_Session__c se : sessions){
            se.Name = Name;
        }
        update sessions;
        
    }
     public static void deleteSession(String sessionId){
        /*Event_Session__c se = [SELECT id,Name FROM Event_Session__c WHERE id = :sessionId];
        
        delete se;*/
        Map<String,Event_Session__c> myMap = new Map<String,Event_Session__c>([SELECT id, Name FROM Event_Session__c]);
        System.debug(' ' + myMap);
    }
     public static void undeleteSession(String sessionId){
        Event_Session__c se = [SELECT id,Name FROM Event_Session__c WHERE id = :sessionId];
        
        undelete se;
    }
}