force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <description>This is a simple description</description>
    <label>Custom Event</label>
    <nameField>
        <label>Custom Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The day the event started</description>
    <inlineHelpText>this is a field to hold information about the day of the event</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event_Session__c/Event_Session__c.object-meta.xml
<CustomObject>
    <description>A subsession</description>
    <label>Event Session</label>
    <nameField>
        <label>Event Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Session__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <description>This is a relationship between father and child</description>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Sessions</relationshipLabel>
    <relationshipName>Event_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End_Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/updateCustomEventFields.cls
public class updateCustomEventFields {
    public static List<Custom_Event__c> updateFieldsMethod(String nameEvent){
        System.debug('Name of the event : ' + nameEvent);
        
        List<Custom_Event__c> customEventList = [SELECT id,Name 
                                                 FROM Custom_Event__c 
                                                 WHERE Name = :nameEvent];
        for(Custom_Event__c ce : customEventList){
            System.debug('Custom Event List ' + ' ' + ce);
        }
        return customEventList;
    }
    
    public static List<Event_Session__c> updateDate(Date startDate, Date endDate){
        
        List<Event_Session__c> EventSessionList = [SELECT id,Name,Start_Date__c,End_Date__c
                                                 FROM Event_Session__c ORDER BY Name];
        for(Event_Session__c es : EventSessionList){
            System.debug('custom event list ' + es);
            
            es.Start_Date__c = startDate;
            es.End_Date__c = endDate;
            
        }
        update eventSessionList;
        System.debug('EventSessionList : ' + eventSessionList);
        return EventSessionList;
    }
    
}