force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <description>This is a simple description</description>
    <label>Custom Event</label>
    <nameField>
        <label>Custom Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Event_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Event_Subtype__c</fullName>
    <label>Event Subtype</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Main_Event_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Football</fullName>
            </value>
            <value>
                <fullName>Cars</fullName>
            </value>
            <value>
                <fullName>National Politics</fullName>
            </value>
            <value>
                <fullName>International Politics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Main_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Main_Event_Type__c</fullName>
    <description>Sport
Politics</description>
    <label>Main Event Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>Politics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The day the event started</description>
    <inlineHelpText>this is a field to hold information about the day of the event</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event_Session__c/Event_Session__c.object-meta.xml
<CustomObject>
    <description>A subsession</description>
    <label>Event Session</label>
    <nameField>
        <label>Event Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Session__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <description>This is a relationship between father and child</description>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Sessions</relationshipLabel>
    <relationshipName>Event_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End_Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CustomTast.cls
public class CustomTast {
	public static void createCustomEvent(Date startDate, Date endDate){
        Custom_Event__c ce = new Custom_Event__c();
        
        ce.Start_Date__c = startDate;
        ce.End_Date__c = endDate;
        
        ce.Main_Event_Type__c = 'Sport';
        ce.Event_Subtype__c = 'Cars';
        
        insert ce;
        System.debug('Id : ' + ' ' + ce.Id);
    }
    public static void createEventSession(){
        List<Custom_Event__c> customEvents = [SELECT id,Name,Start_Date__c, End_Date__c FROM Custom_Event__c];
        
        for(Custom_Event__c ce : customEvents){
            List<Event_Session__c> sessions = new List<Event_Session__c>();
			for(Integer i = 0 ; i <= ce.Start_Date__c.daysBetween(ce.End_Date__c); i++){
            Event_Session__c customSession = new Event_Session__c();
            
                customSession.Start_Date__c = ce.Start_Date__c + i;
                customSession.End_Date__c = ce.End_Date__c + i;
                customSession.Custom_Event__c = ce.Id;
               	sessions.add(customSession);
        	}  
            insert sessions;
        }
    }
}