force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <description>This is a simple description</description>
    <label>Custom Event</label>
    <nameField>
        <label>Custom Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Session__c/Event_Session__c.object-meta.xml
<CustomObject>
    <description>A subsession</description>
    <label>Event Session</label>
    <nameField>
        <label>Event Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Session__c/fields/Custom_Event__c.field-meta.xml
<CustomField>
    <fullName>Custom_Event__c</fullName>
    <description>This is a relationship between father and child</description>
    <label>Custom Event</label>
    <referenceTo>Custom_Event__c</referenceTo>
    <relationshipLabel>Event Sessions</relationshipLabel>
    <relationshipName>Event_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CustomEventCreateEventSessions_test.cls
@isTest
public class CustomEventCreateEventSessions_test {
	@isTest
    public static void createEventSessionsTest(){
        CustomEventController controller = new CustomEventController();
        Custom_Event__c event = controller.createCustomEvent(Date.today(), Date.today().addDays(1));
        
        insert event;
        
        List<Event_Session__c> sessions = [SELECT Name,Id FROM Event_Session__c WHERE Custom_Event__c =: event.Id];
        
        System.assert(sessions.size() == 2);
    }
}